version: "3.3"
services:
  teamcity-db:
    image: postgres:10.2
    container_name: teamcity-db
    ports:
      - "5432:5432"
    volumes:
      - ${DB_DATA_PATH:-~/mount/postgres/teamcity/}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: eX933dISQSLT
  teamcity-server:
    image: jetbrains/teamcity-server:2017.2.2
    container_name: teamcity-server
    ports:
      - "8111:8111"
    volumes:
      - ${DATA_PATH:-~/Workspace/TeamCity/data/}:/data/teamcity_server/datadir
      - ${LOGS_PATH:-~/Workspace/TeamCity/logs/}:/opt/teamcity/logs
  teamcity-agent:
    image: eyupgurel/teamcity-android-agent:2017.2.2
    container_name: teamcity-agent
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    volumes:
      - ${CONF_PATH:-~/Workspace/TeamCity/agent/}:/data/teamcity_agent/conf
    environment:
      - SERVER_URL=http://teamcity-server:8111
  android-emulator:
    image: pinfake/android-emulator-x11
    container_name: android-emulator
    ports:
      - "5555:5555"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /usr/lib:/usr/lib
    environment:
      - DISPLAY=$DISPLAY
    privileged: true

