version: "3.3"
services:
  tmcdb:
    image: postgres:10.4
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - ~/mount/postgres/teamcity/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: eX933dISQSLT
      shared_buffers: 512MB
      max_wal_size: 1500MB
      checkpoint_completion_target: 0.9
      synchronous_commit: 'off'
  tmcs:
    image: eyupgurel/teamcity-server:2018.1
    ports:
      - 8111:8111
    networks:
      - backend
    volumes:
      - ~/Workspace/TeamCity/data/:/data/teamcity_server/datadir
      - ~/Workspace/TeamCity/logs/:/opt/teamcity/logs
  tmca1:
    image: eyupgurel/teamcity-android-node-agent:2018.1
    ports:
      - 9090:9090
    networks:
      - backend
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - ~/Workspace/TeamCity/agent/heavypack/:/data/teamcity_agent/conf
    environment:
      - SERVER_URL=http://tmcs:8111
      - DOCKER_IN_DOCKER=start
      - AGENT_NAME=heavypack
    command:
      - bash /run-services.sh
    privileged: true
  tmca2:
      image: eyupgurel/teamcity-android-node-agent:2018.1
      ports:
        - 9091:9090
      networks:
        - backend
      devices:
        - /dev/bus/usb:/dev/bus/usb
      volumes:
        - ~/Workspace/TeamCity/agent/booster/:/data/teamcity_agent/conf
      environment:
        - SERVER_URL=http://tmcs:8111
        - DOCKER_IN_DOCKER=start
        - AGENT_NAME=booster
      command:
        - bash /run-services.sh
      privileged: true
  android-emulator:
    image: pinfake/android-emulator-x11
    ports:
      - 5554:5554
    networks:
      - backend
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /usr/lib:/usr/lib
    environment:
      - DISPLAY=$DISPLAY
    privileged: true
networks:
  backend:


